version: "3.8"
services:
  abs-metasearch:
    image: ghcr.io/comsuon/abs-metasearch:develop
    container_name: abs-metasearch
    ports:
      - "5555:5555"
    restart: unless-stopped
    env_file:
      - .env
