# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  lint:
    cmds:
      - golangci-lint run

  format:
    cmds:
      - go fmt ./...

  test:
    cmds:
      - |
        go clean -testcache
        go test ./...

  gen:
    cmds:
      - go generate ./...

  build:
    cmds:
      - go build -v -o bin/abs-metasearch

  build:docker:
    cmds:
      - docker build . -t abs-metasearch

  run:
    cmds:
      - go run .

  run:docker:
    deps: [build:docker]
    cmds:
      - |
        docker run --rm \
          --name abs-metasearch \
          -p 5555:5555 \
          --env-file .env \
          abs-metasearch
